# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2768f94dedbaaf2fccdfed72d8d4479c8db81262d4164a92f34a54a95e4dc570fdfb6350f4ea9e054378b2237eac4d136e94a500e690d57199cb8738d877c1a

test:
  secret_key_base: 821c772eefc902fa588126296f44d4d2ed7c5060f451c8aee1c44f11198e45aed638ea638353699d6a7c31531aae1311fb022b240778b7894ae2fbb47a184d16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
